AWSTemplateFormatVersion: 2010-09-09
Description: ChatApp
Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
  Service:
    Type: String
Resources:
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "connectionId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "connectionId"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification:
        SSEEnabled: True
      TableName: !Sub ${Service}-${Environment}