AWSTemplateFormatVersion: 2010-09-09
Description: ChatApp
Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
  Service:
    Type: String
Resources:
  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Service}-Api-Role-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: '/'
      Policies:
      - PolicyName: DynamoDB
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - dynamodb:DeleteItem
              - dynamodb:PutItem
            Resource: 
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${Service}-${Environment}
  CognitoApiRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Service}-Cognito-Api-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: '/'
      Policies:
      - PolicyName: CognitoSignUp
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - cognito-idp:SignUp
              - cognito-idp:ConfirmSignUp
            Resource: "*"